const products = [
    {
        name:'24 Mantra Organic Low Gi Rice',
        unit: '5 kg',
        price: 750,
        discountedPrice: 563,
        discount: 24,
        model: '24 Mantra',
        subcategory: 'top-picks',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/TopPicks/1/1.webp',
        description: 'Cook healthy and delicious meals with 24 Mantra Organic Low Gi Rice. Made from premium quality organic rice, this low glycemic index rice is perfect for maintaining blood sugar levels and promoting overall health. Whether used in pilafs, stir-fries, or curries, 24 Mantra Organic Low Gi Rice is sure to impress with its fluffy texture and authentic taste. Stock up on this essential ingredient and enjoy the benefits of low GI rice in your favorite recipes.',
        origin: 'India',
        life: '12 months',
        manufacturer: 'Sresta Natural Bioproducts Pvt. Ltd.'
    },
    {
        name:'Pansari Kuttu Atta - Buckwheat Millet',
        unit: '500 g',
        price: 160,
        discountedPrice: 111,
        discount: 30,
        model: 'Pansari',
        subcategory: 'top-picks',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/TopPicks/2/1.webp',
        description: "Cook delicious and nutritious meals with Pansari Kuttu Atta - Buckwheat Millet. This premium quality buckwheat flour is perfect for making rotis, pancakes, and other baked goods, offering a rich and nutty flavor to your recipes. Sourced from trusted farmers, it offers superior taste and nutrition. Whether you're cooking traditional Indian cuisine or experimenting with new flavors, Pansari Kuttu Atta is sure to impress!",
        origin: 'India',
        life: '122 days',
        manufacturer: 'Pansari Industry Private Limited'
    },
    {
        name:'Oleev Extra Light Olive Oil - Frying Sauteing & Grilling (Bottle)',
        unit: '500 g',
        price: 2899,
        discountedPrice: 1853,
        discount: 36,
        model: 'Oleev',
        subcategory: 'top-picks',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/TopPicks/3/1.webp',
        description: 'Cook healthy and delicious meals with 24 Mantra Organic Low Gi Rice. Made from premium quality organic rice, this low glycemic index rice is perfect for maintaining blood sugar levels and promoting overall health. Whether used in pilafs, stir-fries, or curries, 24 Mantra Organic Low Gi Rice is sure to impress with its fluffy texture and authentic taste. Stock up on this essential ingredient and enjoy the benefits of low GI rice in your favorite recipes.',
        origin: 'India',
        life: '12 months',
        manufacturer: 'Sresta Natural Bioproducts Pvt. Ltd.'
    },
    {
        name:'Fortune Kachi Ghani Pure Mustard Oil (Jar)',
        unit: '5 l',
        price: 1050,
        discountedPrice: 891,
        discount: 15,
        model: 'Oleev',
        subcategory: 'oil',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/oil/1/1.webp',
        description: "Traditionally extracted from the first press of mustard seeds, Fortune Premium Kachi Ghani Pure Mustard Oil is the ideal choice for preparing delectable dishes. Has a strong aroma and a pungent flavour. Can be used to make pickles as it is a natural preservative that keeps them fresh for a longer duration. Acts as a digestive aid and neutralizes toxins in the body. Contains omega-3 and omega-6 fatty acids that are good for your heart health. Use it for shallow and deep-frying, grilling, roasting, and stir-frying.",
        origin: 'India',
        life: '12 months',
        manufacturer: 'Adani Wilmar Limited'
    },
    {
        name:'Pansari Kachi Ghani Mustard Oil (Bottle)',
        unit: '1 l',
        price: 190,
        discountedPrice: 161,
        discount: 15,
        model: 'Pansari',
        subcategory: 'oil',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/oil/2/1.webp',
        description: "Pansari Kachi Ghani Mustard Oil which is made from superior quality mustard seeds which keeps the delectable aroma intact. Traditionally made using the finest of mustard seeds it has a strong fragrance that adds to the flavour of dishes cooked in it. Has digestive properties that neutralize toxins and keep your stomach healthy. It can be used in fresh pickles as it keeps them fresh for longer. It is a healthy cooking oil designed specially to deliver sharp taste",
        origin: 'India',
        life: '13 months',
        manufacturer: 'PANSARI INDUSTRIES'
    },
    {
        name:'Del Monte Olive Pomace Oil',
        unit: '1 l',
        price: 1100,
        discountedPrice: 889,
        discount: 19,
        model: 'Del Monte',
        subcategory: 'oil',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/oil/3/1.webp',
        description: "Del Monte pomace olive oil is a light oil with neutral taste and flavour and is the most suitable oil for Indian cuisine as it does not change the flavour or taste of any preparation.",
        origin: 'India',
        life: '24 months',
        manufacturer: 'Del Monte Foods Private Limited'
    },
    {
        name:'Rajdhani Besan',
        unit: '500 g',
        price: 78,
        discountedPrice: 62,
        discount: 20,
        model: 'Rajdhani FM',
        subcategory: 'atta-other-flours',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/AttaAndOthers/1/1.webp',
        description: "Besan or Gram Flour made from ground chickpea or channa dal is a wheat-free product wealthy in fiber and nutrients. It is rich in minerals such as zinc and calcium and contains considerable amounts of protein.",
        origin: 'India',
        life: '92 days',
        manufacturer: 'Victoria Foods Pvt Ltd'
    },
    {
        name:'Aashirvaad Select Atta, Made from 100%25 MP Sharbati Wheat for Softer Rotis',
        unit: '500 g',
        price: 710,
        discountedPrice: 559,   
        discount: 21,
        model: 'Aashirvaad',
        subcategory: 'atta-other-flours',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/AttaAndOthers/2/1.webp',
        description: "Crafted from the regal Sharbati wheat, Aashirvaad Select is India's premium atta, lovingly produced for discerning households. This exceptional flour boasts 100% Sharbati wheat from Madhya Pradesh's finest regions, known for its golden sheen and uniform grain size. Each Sharbati grain has a distinct golden sheen, that makes Select Atta truly special. The sun-kissed fields of MP, blessed with ideal rainfall, yield sharbati wheat atta that absorbs more water, resulting in rotis that are delightfully sweet and irresistibly soft. With Aashirvaad Select, savour softer rotis that maintain their texture longer, bringing the perfect blend of taste and convenience to your dining table.",
        origin: 'India',
        life: '90 days',
        manufacturer: 'ITC Limited'
    },
    {
        name:'Aashirvaad Atta - Shudh Chakki Atta, No Maida (Pouch)',
        unit: '10 kg',
        price: 479,
        discountedPrice: 439,   
        discount: 8,
        model: 'Aashirvaad',
        subcategory: 'atta-other-flours',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/AttaAndOthers/3/1.webp',
        description: "Launched on 27th May 2002, Aashirvaad Shudh Chakki Atta has now become No. 1 in branded packaged atta across the country. Behind every Aashirvaad pack are the Indian farmers and Aashirvaad experts who have made the atta with extra care. The 4-step advantage process of sourcing, cleaning, grinding ensures zero human contact with the atta.",
        origin: 'India',
        life: '89 days',
        manufacturer: 'ITC Limited'
    },
    {
        name:'Tata Sampann Unpolished Toor Dal%2FArhar Dal',
        unit: '1 kg',
        price: 269,
        discountedPrice: 241,   
        discount: 10,
        model: 'Tata Sampann',
        subcategory: 'dals-pulses',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/DalsAndPulses/1/1.webp',
        description: "Tata Sampann Toor Dal is delicious in taste. It does not undergo any artificial polishing with water, oil or leather, thereby retaining their goodness and wholesome character. It is used in a variety of salads, soups and many more.",
        origin: 'India',
        life: '12 Months',
        manufacturer: 'Tata Chemicals Limited'
    },
    {
        name:'Rajdhani Rajma Chitra',
        unit: '1 kg',
        price: 245,
        discountedPrice: 209,   
        discount: 14,
        model: 'Rajdhani',
        subcategory: 'dals-pulses',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/DalsAndPulses/2/1.webp',
        description: "Rajdhani Rajma is superior to the regular rajma and very soft feel and more delicate flavor and is white in color. It is low in fat & cholesterol, high in dietary fiber and rich in protein.",
        origin: 'India',
        life: '6 Months',
        manufacturer: 'Victoria Foods Pvt Ltd'
    },
    {
        name:'Rajdhani Chana Kabuli',
        unit: '1 kg',
        price: 221,
        discountedPrice: 190,   
        discount: 14,
        model: 'Rajdhani',
        subcategory: 'dals-pulses',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/DalsAndPulses/3/1.webp',
        description: "Kabuli channa or garbanzo beans are pale brown colored, sensitive, bland and starchy tasting, spongy and creamy textured legumes are a wealthy source of minerals such as magnesium, phosphorous, calcium, iron, potassium and importantly, molybdenum. They are utilized to make delicacies like falafels, Curried Chole and hummus.",
        origin: 'India',
        life: '6 Months',
        manufacturer: 'Victoria Foods Pvt Ltd'
    },
    {
        name:'Fortune Rozana Basmati Rice',
        unit: '1 kg',
        price: 585,
        discountedPrice: 585,   
        discount: 32,
        model: 'Fortune',
        subcategory: 'rice-more',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/RiceAndMore/1/1.webp',
        description: "Fortune brings to you the most special basmati - Fortune Super Basmati Rice. It is specially aged to help every grain acquire the best basmati characteristic. Every slender grain of super basmati rice is carefully picked, aged, dried, de-husked, processed, graded and sorting machine at our state-of-the-art milling plant.",
        origin: 'India',
        life: '24 Months',
        manufacturer: 'Adani Wilmar Limited'
    },
    {
        name:'Mangat Ram Poha Pouch',
        unit: '500 g',
        price: 69,
        discountedPrice: 56,   
        discount: 18,
        model: 'Mangat',
        subcategory: 'rice-more',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/RiceAndMore/2/1.webp',
        description: "Mangat Ram White Lobia 500 g Who doesn't love that savoury flavour of home cooked food? Now with Mangat Ram White Lobia, cooking your favourite lobia recipe is simpler than ever. Made of premium quality beans, this product from Mangat Ram is something you definitely cannot ignore.",
        origin: 'India',
        life: '122 days',
        manufacturer: 'Mangat Ram Dal Mills Pvt. Ltd'
    },
    {
        name:'Fortune Hamesha Mini Dubar Basmati Rice',
        unit: '5 kg',
        price: 465,
        discountedPrice: 355,   
        discount: 23,
        model: 'Fortune',
        subcategory: 'rice-more',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/RiceAndMore/3/1.webp',
        description: "Fortune brings to you the most special basmati rice- biryani special. On cooking, it becomes exceptionally long fluffy and full of flavour. The result is an irresistible serving that delight everyone’s heart through its appearance and taste. Whether it's Hyderabadi or Lucknowi the non-sticky grain structure, makes the best of every biryani.",
        origin: 'India',
        life: '24 Months',
        manufacturer: 'Adani Wilmar Limited'
    },
    {
        name:'Mother Dairy Cow Ghee (Carton)',
        unit: '1 l',
        price: 685,
        discountedPrice: 634,   
        discount: 7,
        model: 'Mother Dairy',
        subcategory: 'ghee',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/Ghee/1/1.webp',
        description: "In Ayurveda, Cow ghee is believed to be the best for human consumption. It is considered as rasayana, a rejuvenating and longevity promoting food. It is a rich source of Vitamin A which is essential for vision, body growth, bone metabolism and immune function.",
        origin: 'India',
        life: '9 Months',
        manufacturer: 'Mother Dairy Fruit & Vegetable Pvt Ltd'
    },
    {
        name:'Amul Cow Ghee (Carton)%2FRefill',
        unit: '1 l',
        price: 650,
        discountedPrice: 577,   
        discount: 11,
        model: 'Amul Products',
        subcategory: 'ghee',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/Ghee/2/1.webp',
        description: "Amul Cow Ghee is saturated with healthy fats with a strong aroma that makes any dish yummy and droll-worthy and is ideal for cooking and garnishing purposes.",
        origin: 'India',
        life: '12 months',
        manufacturer: 'Gujarat Co-Operative Milk Marketing Federation'
    },
    {
        name:'Barosi A2 Desi Cow Ghee',
        unit: '1 l',
        price: 1899,
        discountedPrice: 1311,   
        discount: 30,
        model: 'Barosi',
        subcategory: 'ghee',
        category: 'atta-rice-oils-dals',
        img1: '/products/atta/Ghee/3/1.webp',
        description: "Barosi ghee is made using fresh & pure milk procured from our own farms using the bilona padati method. The milk is converted into curd and the curd is slowly churned to make butter. The butter is then refined and carbohydrates, proteins, casein, lactose, impurities and water are removed, leaving only pure fat or oil.",
        origin: 'India',
        life: '12 Months',
        manufacturer: 'Landwirt India Private Limited'
    },
    {
        name:'The Khao Project Bhut Jolokia Chilli Oil - Mild',
        price: 300,
        discountedPrice: 225,   
        discount: 25,
        model: 'Khao Project',
        subcategory: 'top-picks',
        category: 'breakfast',
        img1: '/products/breakfast/topPicks/1/1.webp',
        origin: 'India',
        life: '12 Months',
        manufacturer: 'The Khao Project'
    },
    {
        name:'The Khao Project Roasted Garlic & Dill Hummus',
        price: 200,
        discountedPrice: 170,   
        discount: 15,
        model: 'Khao Project',
        subcategory: 'top-picks',
        category: 'breakfast',
        img1: '/products/breakfast/topPicks/2/1.webp',
        origin: 'India',
        description:' The Khao Project Roasted Garlic and Dill Hummus Dip & Spread is a preservative free and a healthy snacking option. It is high in several important nutrients, including fibre & protein. It is fresh, delicious & made with Olive oil. Olive oil is rich in healthy monosaturated fats, contains large amounts of antioxidants and has strong anti-inflammatory properties. It is tasty, low fat, ready to eat snack and ideal for mid-day meals, evening snacks, parties & get togethers. Your healthy food for a healthy diet!',
        life: '90 days',
        manufacturer: 'PRAVIVIKTA CONSUMER FOODS LLP'
    },
    {
        name:'The Khao Project Roasted Red Pepper Hummus',
        price: 200,
        discountedPrice: 170,   
        discount: 15,
        model: ' Khao Project',
        subcategory: 'top-picks',
        category: 'breakfast',
        img1: '/products/breakfast/topPicks/3/1.webp',
        origin: 'India',
        life: '90 days',
        manufacturer: 'The Khao Project'
    },
    {
        name:'Kellogg%E2%80%99s Multigrain Chocos %7C More Chocolatey %7C No-Maida',
        price: 525,
        discountedPrice: 485,   
        discount: 7,
        unit:'1.1 kg',
        model: 'Kellogg’s',
        subcategory: 'breakfast-cereals',
        category: 'breakfast',
        img1: '/products/breakfast/breakfast/1/1.webp',
        origin: 'India',
        life: '9 months',
        FSSAILicense : 10013022002031,
        manufacturer: 'Kelloggs India Pvt Ltd',
        manufacturerAddress: 'Kelloggs India Pvt Ltd, Plot No. L2 & L3, Taloja MIDC, Dist. Rajgad, Maharashtra - 410208.',
        ingredients: " Whole Wheat Flour (28%), Sugar, Wheat Flour, Corn Flour, Cocoa Solids (de-fatted 5%), Edible Vegetable Oil, Minerals, Malt Extract, Iodized Salt,vitamins, Colour (ins 150d) And Antioxidant (ins 320)contains Permitted Natural Colour & Added Flavours(nature-identical & Artificial Flavouring Substances-cream)",
        description:"Meet our NEW Kellogg’s Multigrain Chocos! It is loaded with multigrain & is Maida-Free. It is much more chocolatey than before which kids will love even more. This product is high in protein, fibre, calcium, iron & essential vitamins like B1,B2,B3,B6. Kellogg’s Multigrain Chocos has no added preservatives. It is made of grains – Wheat, Jowar, Corn & Rice.",
    },
    {
        name:"Kellogg's Almonds And Cranberries Granola",
        price: 390,
        unit:'460 g',
        discountedPrice: 366,   
        discount: 6,
        model: 'Kellogg’s',
        subcategory: 'breakfast-cereals',
        category: 'breakfast',
        img1: '/products/breakfast/breakfast/2/1.webp',
        origin: 'India',
        life: '9 months',
        manufacturer: 'Kelloggs India Pvt Ltd',
        manufacturerAddress: 'Kelloggs India Pvt Ltd, Plot No. L2 & L3, Taloja MIDC, Dist. Rajgad, Maharashtra - 410208.',
        ingredients: "Rolled Oats (25.1%), Candied Fruit and Nut (24%) {Candied Cranberry (14%), Almonds (10%)}, Sugar, Oat Flour (10.7%) Edible Vegetable Oil (Palmolein), Rice (4.2%) Whole Wheat (3.9%), Rice Flour (2.7%), Liquid Glucose, Corn Flour (1.8%), Honey, Malt Extract, Wheat Bran (0.6%), Wheat Flour (0.5%), Iodized Salt, Dextrose, Barley Flour (0.1%), Vitamins, Raising Agent (INS 500ii), Minerals, Antioxidant (INS 320). It contains added flavours (Nature identical and artificial cream flavouring substances). It contains Gluten, Almonds and it may contain traces of Soy and Milk.",
        description: "New Kelloggs Crunchy Granola is an irresistibly tasty way to start your day. Enjoy baked, multigrain clusters of whole-grain oats, wheat, corn, rice and barley, generously loaded with real almonds and cranberries."
    },
    {
        name:'Kellogg%E2%80%99s Multigrain Chocos %7C More Chocolatey %7C No-Maida 250g',
        price: 148,
        discountedPrice: 141,   
        discount: 4,
        unit:'250 g',
        model: 'Kellogg’s',
        subcategory: 'breakfast-cereals',
        category: 'breakfast',
        img1: '/products/breakfast/breakfast/3/1.webp',
        origin: 'India',
        life: '9 months',
        manufacturer: 'Kelloggs India Pvt Ltd',
        manufacturerAddress: 'Kelloggs India Pvt Ltd, Plot No. L2 & L3, Taloja MIDC, Dist. Rajgad, Maharashtra - 410208.',
        ingredients: "Whole wheat flour (29%), Wheat flour, Sugar cocoa solids (de-fatted 5%), (INS 150d), Vitamins, Minerals, Antioxidant (INS 320).",
    },
    {
        name:"Nando's Sauce - Hot Peri Peri",
        discountedPrice: 390,   
        unit:'250 g',
        model: 'Kellogg’s',
        subcategory: 'ketchup-sauces',
        category: 'breakfast',
        img1: '/products/breakfast/ketchup/1/1.webp',
        origin: 'Netherlands',
        life: '24 months',
        manufacturer: 'Nandos',
    },
    {
        name:"Maggi Hot & Sweet - Tomato Chilli Sauce",
        discountedPrice: 185,   
        unit:'1 kg',
        model: 'Maggi',
        subcategory: 'ketchup-sauces',
        category: 'breakfast',
        img1: '/products/breakfast/ketchup/2/1.webp',
        description: 'Nestle brings to you MAGGI Hot & Sweet Tomato Chilli Sauce to add a delicious and spicy tang to your favourite dishes. The unique blend of this tomato sauce with tangy tomatoes and red chillies makes for a spicy and tangy flavour. The hero to your snacks and the best accompaniment to a boring meal. MAGGI Chilli Sauce goes well with everything from samosas, noodles to pakodas, and plain chapatis. Also great with snacks like burgers, fries, pizza, pasta, and more. MAGGI Hot and Sweet Tomato Chilli Sauce is fresh and healthy.',
        FSSAILicense : 'FSSAI No 10012025000032',
        ingredients:'Water, Sugar, Tomato paste (11.9%), Red chilli puree (6.6%), Iodized salt, Acidity regulator (260), Starch, Mixed spices, Garlic powder, Thickener (415), Onion powder and Preservatives (211).',
        origin: 'India',
        life: '18 months',
        manufacturer: 'Nestle India Ltd',
        manufacturerAddress: 'Nestle India Ltd, Nestle House, Jacaranda Marg M Block, DLF City Phase II, National Highway 8, Gurgaon 122 002, India.',
        nutritionalInfo:'Serve - 1tbsp (9g) Energy - 135 kcal Protein - 0.4 g Carbohydrate - 33.8 g Total Sugars - 33.3 g Added Sugars - 32 g Total Fat - 0.0 g Sodium - 807.7 mg' 
    },
    {
        name:"WOW Life Science Organic Apple Cider Vinegar",
        discountedPrice: 390,   
        price:749,
        discount: 41,
        unit:'750 ml',
        model: 'WOW Skin Science',
        subcategory: 'ketchup-sauces',
        category: 'breakfast',
        img1: '/products/breakfast/ketchup/3/1.webp',
        description:"WOW Life Science Organic Apple Cider Vinegar is a natural and organic vinegar made from high-quality, handpicked apples. Rich in acetic acid and essential nutrients, this apple cider vinegar offers numerous health benefits, including supporting weight management, improving digestion, and promoting overall wellness. Incorporate it into your daily routine as a refreshing drink or use it in cooking and salad dressings for added flavor and nutrition.",
        life: '18 months',
        manufacturer: 'BODYCUPID PRIVATE LIMITED',
    },
    {
        name:"MuscleBlaze Fit High Protein Oats (Dark Chocolate)",
        discountedPrice: 582,   
        price:725,
        discount: 19,
        unit:'1 kg',
        model: 'MuscleBlaze',
        subcategory: 'muesli-oats',
        category: 'breakfast',
        img1: '/products/breakfast/muesli/1/1.webp',
        description: "You can rest easy with MuscleBlaze Fit High Protein Oats which is un-berry-ably good and defi-nut-ly awesome for your crazy mornings! It is great for vegetarians or anyone looking to add more protein to their diet, it provides 22 g protein per 100 g. It is a vegetarian source of protein that is also high in fibre and antioxidants. High fibre helps to maintain bowel movement and benefits heart health. Both protein and fibre are fulfilling so you are likely to eat less which is great for weight management.",
        life: '9 months',
        origin:"India",
        howToUse: "For every cup of Oats (50 g), add 1 1/2 cups (250 ml) of water/milk in a pan. Cook for 3 minutes on a medium flame or microwave for 3 minutes on fullpower.",
        manufacturer: 'VLS Foods Private Limited',
        manufacturerAddress: 'H-550,551,716, Phase – 1, Industrial Area, Bhiwadi, Alwar, Rajasthan-301019',
    },
    {
        name:"Kellogg%E2%80%99s Muesli Nuts Delight 12-in-1 Power Breakfast",
        discountedPrice: 503,   
        price:830,
        discount: 39,
        unit:'1 kg',
        model: "Kellogg's",
        subcategory: 'muesli-oats',
        category: 'breakfast',
        img1: '/products/breakfast/muesli/2/1.webp',
        description: "Kellogg’s Muesli Nuts Delight 12-in-1 Power Breakfast is a delicious and nutritious breakfast option. Made with a blend of whole grains, nuts, and dried fruits, this muesli is packed with fiber, protein, and essential nutrients. Enjoy the crunchy texture of nuts and the natural sweetness of fruits in every bite. Start your day on a healthy note with Kellogg’s Muesli Nuts Delight 12-in-1 Power Breakfast.",
        life: '9 months',
        manufacturer: 'Kellogg India Private Limited',

    },
    {
        name:"Kellogg%E2%80%99s Millet Muesli - India'S No.1 Muesli",
        discountedPrice: 405,   
        price:710,
        discount: 42,
        unit:'1 kg',
        model: "Kellogg's",
        subcategory: 'muesli-oats',
        category: 'breakfast',
        img1: '/products/breakfast/muesli/3/1.webp',
        description: "Kellogg'S Millet Muesli - India'S No.1 Muesli",
        life: '9 months',
        origin:'India'

    },
    {
        name:"Veeba Mayonnaise Smart",
        price:179,
        discountedPrice: 147,   
        discount: 17,
        unit:'750 g',
        model: "Veeba",
        subcategory: 'honey-spreads',
        category: 'breakfast',
        img1: '/products/breakfast/honey/1/1.webp',
        description: "Veeba Mayonnaise Smart: Veeba Mayonnaise Smart is a delicious and creamy condiment that adds flavor to your sandwiches, salads, and wraps. Made with high-quality ingredients, this mayonnaise is perfect for elevating the taste of your favorite dishes. Whether you use it as a dip or a spread, Veeba Mayonnaise Smart is sure to delight your taste buds.",
        life: '6 months',
        manufacturer: 'Veeba',
    },
    {
        name:"Saffola Honey Active, Made with Sundarban Forest Honey",
        price:495,
        discountedPrice: 347,   
        discount: 29,
        unit:'1 kg',
        model: "Saffola",
        subcategory: 'honey-spreads',
        category: 'breakfast',
        img1: '/products/breakfast/honey/2/1.webp',
        description: "Honey is a natural food and comes with tons of uses and benefits and should be used in its pure form. Pure Honey is also a healthy alternative to sugar. However, not all honey sold in the market are alike! Some are pure, while others may be highly adulterated. Saffola Honey is natural honey in its purest form & each bottle contains natural antioxidants, has No Added Sugar.",
        life: '18 months',
        ingredients:'Honey(100%)',
        origin:'India',
        manufacturer: 'Ameya Foods',
        FSSAILicense : '1.0012E+13',
        manufacturerAddress: ' Ameya Foods, S. F. No-315, Angels Garden, Nagamanaicken Palayam, Pattanam (PO), Ondipudur (Via), Coimbatore - 641016.',
        nutritionalInfo:'100 gEnergy: 325kcalTotal fat 0 gCarbohydrate: 81gTotal sugar: 81gProtien: 0. 25 g' 
    },
    {
        name:"Nutella Hazelnut Spread with Cocoa",
        price:399,
        discountedPrice: 359,   
        discount: 10,
        unit:'350 g',
        model: "Nutella",
        subcategory: 'honey-spreads',
        category: 'breakfast',
        img1: '/products/breakfast/honey/3/1.webp',
        description: "Enjoy the beloved hazelnut spread with cocoa with your family and friends. Give the day a positive start with one spread(≈15g) of Nutella on bread at breakfast or create delicious recipes for special days.",
        life: '12 months',
        ingredients:'SUGAR, PALM OIL, HAZELNUTS (13%), SKIMMED COW MILK POWDER (8.7%), LOW FAT COCOA POWDER (7.4%), EMULSIFIER (LECITHIN - INS 322), NATURE-IDENTICAL FLAVOURING SUBSTANCE – VANILLIN.',
        origin:'Turkey',
        manufacturer: 'Ferrero Ind',
        FSSAILicense : '10013022001381',
        manufacturerAddress: 'Ferrero Türkiye Çikolata ve Tarım Ürünleri San. Ve Dış Tic. A.Ş., Manisa OSB V.Kısım Ferrero Cad. No: 3 Manisa, Turkey.',
        nutritionalInfo:'Per 100 g: Energy 539 kcal, Protein 6.3 g, Carbohydrates 57.5 g, Total Sugars 56.3 g, Added Sugars 49.8 g, Total Fat 30.9 g, Saturated Fat 10.6 g, Trans Fat 0.1 g, Cholesterol 4 mg, Sodium 42 mg. Per serve %RDA: Energy 4%, Protein 2%, Carbohydrates -, Total Sugars -, Added Sugars 15%, Total Fat 7%, Saturated fat 7%, Trans Fat 0%, Cholesterol -, Sodium 0%. Serving size: 15 g, Number of servings per pack: 23' 
    },
    {
        name:"MyFitness Chocolate Peanut Butter Crunchy",
        price:689,
        discountedPrice: 565,   
        discount: 17,
        unit:'1.25 g',
        model: "MyFitness",
        subcategory: 'peanut-butter',
        category: 'breakfast',
        img1: '/products/breakfast/peanut/1/1.webp',
        description: "Myfitness Crunchy Chocolate Peanut Butter is healthy and nutritious. This peanut butter is a high source of Vitamin E and proteins. It is made with natural peanuts, dark chocolate, sugar and salt. This peanut butter is flavourful. Now savour the excellent taste of chocolate and crunchy peanut butter.",
        life: '24 months',
        origin:'India',
        manufacturer: 'SuperNutri Foods',
        manufacturerAddress: 'SuperNutri Foods, Palitana Road, Talaja 364140, Gujarat.',
    },
    {
        name:"MyFitness Olympia Edition Crispy Dark Chocolate Peanut butter with Added Whey",
        price:689,
        discountedPrice: 565,   
        discount: 17,
        unit:'1.25 kg',
        model: "MyFitness",
        subcategory: 'peanut-butter',
        category: 'breakfast',
        img1: '/products/breakfast/peanut/2/1.webp',
        description: "Myfitness Crunchy Chocolate Peanut Butter is healthy and nutritious. This peanut butter is a high source of Vitamin E and proteins. It is made with natural peanuts, dark chocolate, sugar and salt. This peanut butter is flavourful",
        life: '12 months',
        origin:'India',
        manufacturer: 'SuperNutri Foods',
        manufacturerAddress: 'SuperNutri Foods, Palitana Road, Talaja 364140, Gujarat.',
    },
    {
        name:"MuscleBlaze Chocolate Peanut Butter (Crunchy)",
        price:599,
        discountedPrice: 449,   
        discount: 25,
        unit:'1 kg',
        model: "MuscleBlaze",
        subcategory: 'peanut-butter',
        category: 'breakfast',
        img1: '/products/breakfast/peanut/3/1.webp',
        description: "Everything's better with chocolate so why should your peanut butter be any different? Get the best of dark chocolate with MuscleBlaze Fit Chocolate Peanut Butter. A truly guilt-free snacking experience with your customized recipes is a fun way to get the energy boost you need to power through your day. Protein helps build muscles, increases muscle recovery, and keeps you full for longer. Fibre supports weight management and enhances overall digestive health.",
        life: '12 months',
        origin:'India',
        howToUse:"02 Tablespoons of this product give as much protein as 3 egg whites. Sp go ahead spread it on a slice of bread or have it the way you love.",
        manufacturer: 'Mother Nutri Foods Private Limited',
        manufacturerAddress: 'Survey No. 276/1, Opp. Petrol Pump, Mahuva- Bhavnagar Highway, Village : Otha, Ta : Mahuva, Bhavnagar, Gujarat-364295',
    },
    {
        name:"iD Idli & Dosa Batter",
        discountedPrice: 120,   
        unit:'1 kg',
        model: "iD Idli",
        subcategory: 'batter-mixes',
        category: 'breakfast',
        img1: '/products/breakfast/batter/1/1.webp',
        description: "iD Idli and Dosa Batter will make sure that the magic of age-old tradition is not lost by giving you the wholesomeness of the unsophisticated home-style food. Only fresh and high-quality ingredients used and no added preservatives. With this ready-made batter, everyone can make a delicious breakfast. Save time and energy on making the batter from scratch. Make soft and fluffy idlis or crispy dosas in a jiffy.",
        life: '9 Days',
        origin:'India',
        ingerdients:"Rice, Urad Dal, Methi Seeds, Ro-Purified Water and Low Sodium Salt",
        howToUse:"02 Tablespoons of this product give as much protein as 3 egg whites. Sp go ahead spread it on a slice of bread or have it the way you love.",
        manufacturer: 'iD Fresh Food India Pvt Ltd',
        manufacturerAddress: 'iD Fresh Food India Pvt Ltd, Sy. Nos. 515/2, 515/3, 515/4, 516/2, 516/3, 516/4, 533, Madivala Village, Kasaba Hobli, Attibele, Anekal Taluk, Bangalore -562107, Karnataka.',
        nutritionalInfo:" Energy 143.35kcal; Protein 5.5g; Fat 1.6g; Saturated Fatty Acid 0.68g; MUFA 0.52g; Sugar 0g; PUFA 0.3g; Trans Fatty Acid 0g; Cholesterol 0mg; Carbohydrates 26.3g; Sodium 92mg;",
    },
    {
        name:"iD Idli & Dosa Batter 2kg",
        discountedPrice: 149,   
        price: 190,   
        unit:'2 kg',
        discount:21,
        model: "iD Idli",
        subcategory: 'batter-mixes',
        category: 'breakfast',
        img1: '/products/breakfast/batter/2/1.webp',
        description: "iD Idli and Dosa Batter will make sure that the magic of age-old tradition is not lost by giving you the wholesomeness of the unsophisticated home-style food. Only fresh and high-quality ingredients used and no added preservatives. With this ready-made batter, everyone can make a delicious breakfast. Save time and energy on making the batter from scratch. Make soft and fluffy idlis or crispy dosas in a jiffy.",
        life: '9 Days',
        origin:'India',
        ingerdients:"Rice, Urad Dal, Methi Seeds, Ro-Purified Water and Low Sodium Salt",
        howToUse:"02 Tablespoons of this product give as much protein as 3 egg whites. Sp go ahead spread it on a slice of bread or have it the way you love.",
        manufacturer: 'iD Fresh Food India Pvt Ltd',
        manufacturerAddress: 'iD Fresh Food India Pvt Ltd, Sy. Nos. 515/2, 515/3, 515/4, 516/2, 516/3, 516/4, 533, Madivala Village, Kasaba Hobli, Attibele, Anekal Taluk, Bangalore -562107, Karnataka.',
        nutritionalInfo:" Energy 143.35kcal; Protein 5.5g; Fat 1.6g; Saturated Fatty Acid 0.68g; MUFA 0.52g; Sugar 0g; PUFA 0.3g; Trans Fatty Acid 0g; Cholesterol 0mg; Carbohydrates 26.3g; Sodium 92mg;",
    },
    {
        name:"MTR Rice Idly Breakfast Mix",
        discountedPrice: 135,   
        price:145,
        unit:'500 g',
        discount:6,
        model: "MTR",
        subcategory: 'batter-mixes',
        category: 'breakfast',
        img1: '/products/breakfast/batter/3/1.webp',
        FSSAILicense : 'FSSAI No 10012043000145',
        description: "Soft, fluffy, light-as-airidlis. A delicious traditional break fast ready in an instant.",
        life: '12 months',
        origin:'India',
        manufacturer:'MTR Foods Pvt. Ltd',
        manufacturerAddress: 'MTR Foods Pvt. Ltd, # 80 Bommasandra Industrial Area, Hebbagodi, Anekal Taluk Bengaluru 560099.',
    },
    {
        name:"Taj Mahal Tea",
        discountedPrice: 610,   
        price:710,
        unit:'1 kg',
        discount:14,
        model: "Taj Mahal",
        subcategory: 'tea-coffee',
        category: 'breakfast',
        img1: '/products/breakfast/tea/1/1.webp',
        description: " Taj Mahal Tea 500 g (Carton) Over 50 Glorious years of Excellence, When the history of tea is written down, 1966 will be a celebrated chapter . For in that year, Brooke Bond Taj Mahal Tea was born, with a promise - To foster excellence in each tea cup. Fifty years on, we have not forgotten that promise. As an age old brand, we have built credential of Great Tasting tea by focusing on our consistently superior quality. Every Taj Mahal cup is created by tea tasters who approve the blend by tasting 1000s of teas then graded and blended to perfection.",
        life: '12 months',
        origin:'India',
        ingerdients:'Tea Leaves',
        manufacturer:'Hindustan Unilever Ltd',
        manufacturerAddress: 'Hindustan Unilever Limited Levercare, Po Box 14760, Mumbai 400099.',
    },
    {
        name:"Tata Tea Premium Tea",
        discountedPrice: 244,   
        price:270,
        unit:'500 g',
        discount:9,
        model: "Tata Tea",
        subcategory: 'tea-coffee',
        category: 'breakfast',
        img1: '/products/breakfast/tea/2/1.webp',
        description: "Chai is more than a cup of tea; rather it is an integral part of the culture and life of every Indian. While drinking chai is enjoyed across the country, people like their cup in India vary across regions. Tata Tea Premium- Desh ki Chai, sourced solely from India, understands these varying taste preferences and hence our tea experts have crafted a unique blend that chai lovers across India will enjoy. Blended since 1985.",
        life: '12 months',
        origin:'India',
        ingerdients:'Tea',
        manufacturer:'Tata Global Beverages Ltd',
        manufacturerAddress: 'Tata Global Beverages Ltd, 3rd Floor Block C, Kirloskar Business Park, Hebbal, Bengaluru 560024.',
    },
    {
        name:"Sleepy Owl French Vanilla Instant Coffee 100%25 Arabica",
        discountedPrice: 471,   
        price:595,
        unit:'100 g',
        discount:20,
        model: "Sleepy Owl",
        subcategory: 'tea-coffee',
        category: 'breakfast',
        img1: '/products/breakfast/tea/3/1.webp',
        description: "Sleepy owl french vanilla premium instant coffee, contains micro grounds of our signature beans. This preserves a genuine aroma of fresh coffee and brews a rich cup in seconds. These soluble coffee crystals are made from only 100% arabica coffee.",
        life: '18 months',
        origin:'India',
        FSSAILicense : '13321999000263',
        ingredients:'Instant Coffee, Roasted & Ground Coffee, Contains Added Nature Identical Flavour - French Vanilla.',
        manufacturer:'Sleepy Owl Coffee Pvt',
        manufacturerAddress: 'Sleepy Owl Coffee Pvt. Ltd, Y-31, Okhla Industrial Area, Phase 2, Delhi - 110020.',
    },
    {
        name:"Chukde Green Cardamom",
        discountedPrice: 321,   
        price:400,
        unit:'50 g',
        discount:19,
        model: "Chukde Green",
        subcategory: 'top-picks',
        category: 'masala-dry-fruits',
        img1: '/products/masala/topPicks/1/1.webp',
        description: "Chukde Green cardamom is used to flavour curry dishes, meat seasoning, daals and rice dishes. It adds an amazing taste to your food making it even more delicious.",
        life: '12 months',
        origin:'India',
        manufacturer:'Lifestyle Foods Pvt Ltd',
        manufacturerAddress: '3rd Floor, B-63 Prashant Vihar Road New Delhi 110085, India',
    },
    {
        name:"Happilo Premium International Queen Kalmi Dates",
        discountedPrice: 235,   
        price: 335,
        unit:'200 g',
        discount: 29,
        model: "Happilo",
        subcategory: 'top-picks',
        category: 'masala-dry-fruits',
        img1: '/products/masala/topPicks/2/1.webp',
        description: "Happilo Kalmi Dates, also known as Khajoor, is one of the worlds most delicious farm-fresh dates and are natural, tasty and healthy.It is a superfood for super-high energy levels.",
        life: '9 months',
        origin:'India',
        manufacturer:'Happilo International Pvt Ltd',
        ingredients: "Dates (Kalmi)",
        manufacturerAddress: 'Happilo International Pvt Ltd, 7, 1st floor, Yeshwantpur, Bangalore 560022.',
    },
    {
        name:"Tata Sampann 100%25 Pure California Almondswhole",
        discountedPrice: 979,   
        price:1310,
        unit:'50 g',
        discount:25,
        model: "Tata Sampann",
        subcategory: 'top-picks',
        category: 'masala-dry-fruits',
        img1: '/products/masala/topPicks/3/1.webp',
        description: "Tata Sampann 100% Pure California Almonds Whole - Enjoy the natural goodness of Tata Sampann 100% Pure California Almonds Whole. These whole almonds are sourced from California and are rich in essential nutrients, including protein, fiber, and healthy fats. With their crunchy texture and delicious flavor, they make a satisfying and nutritious snack option for any time of day.",
        life: '12 months',
        origin:'India',
        manufacturer:'TCPL',
    },
    {
        name:"Catch Dhania Powder",
        discountedPrice: 69,   
        price: 84,
        unit:'200 g',
        discount: 17,
        model: "Catch",
        subcategory: 'powders-pastes',
        category: 'masala-dry-fruits',
        img1: '/products/masala/powders/1/1.webp',
        description: "Catch Coriander Powder is sourced from the best core spice growing areas of Ramganj & Kota (Rajasthan), making your food taste the best. It gives a perfect aroma and colour to dishes making them taste scrumptious.",
        ingredients: ' Coriander/Dhaniya Powder',
        life: '12 months',
        origin:'India',
        FSSAILicense : 'FSSAI No 10016011003518',
        manufacturer:'DS SPICECO PVT LTD',
        manufacturerAddress:'DS SPICECO PVT LTD, B - 6, 17, 18, 19 SECTOR - 3 NOIDA 201301 UP',
    },
    {
        name:"Catch Dhania Powder(200 gms), Catch Red Chilli Powder(200 gms) & Catch Turmeric Powder(200 gms) Combo",
        discountedPrice: 244,   
        price: 296,
        unit:'3 combo',
        discount: 17,
        model: "Catch",
        subcategory: 'powders-pastes',
        category: 'masala-dry-fruits',
        img1: '/products/masala/powders/2/1.webp',
        description: "Catch Dhania Powder(200 gms), Catch Red Chilli Powder(200 gms) & Catch Turmeric Powder(200 gms) Combo",
    },
    {
        name:"MDH Deggi Mirch Powder",
        discountedPrice: 111,   
        price: 120,
        unit:'100 g',
        discount: 7,
        model: "MDH",
        subcategory: 'powders-pastes',
        category: 'masala-dry-fruits',
        img1: '/products/masala/powders/3/1.webp',
        description: "MDH deggi mirch is made from the finest chilies. It not only imparts a spicy hot flavor to cooked dishes, but also lends a wonderful rich red color. This spice is also replete with nutrients which are good for your health. Coming from the house of MDH, which is known for its vast offering of spices, this masala is a must for Indian kitchens.",
        ingredients: ' Coriander/Dhaniya Powder',
        life: '13 months',
        origin:'India',
        manufacturer:'Mahashian Di Hatti Pvt Ltd',
        manufacturerAddress:' Mahashian Di Hatti Pvt Ltd, Dl 9/44 Kirti Nagar Industrial Area New Delhi 110015.',
    },
    {
        name:"Tmi Colman Cashew 320N",
        discountedPrice: 536,   
        price: 820,
        unit:'50 g',
        discount: 34,
        model: "Tmi",
        subcategory: 'dry-fruits-nuts',
        category: 'masala-dry-fruits',
        img1: '/products/masala/dryFruits/1/1.webp',
        life: '180 days',
        origin:'India',
    },
    {
        name:"Tmi Colman Raisins Premium",
        discountedPrice: 173,   
        price: 299,
        unit:'500 g',
        discount: 42,
        model: "Tmi",
        subcategory: 'dry-fruits-nuts',
        category: 'masala-dry-fruits',
        img1: '/products/masala/dryFruits/2/1.webp',
        life: '120 days',
        origin:'India',
    },
    {
        name:"Tmi Colman Almond",
        discountedPrice: 408,   
        price: 565,
        unit:'500 g',
        discount: 27,
        model: "Tmi",
        subcategory: 'dry-fruits-nuts',
        category: 'masala-dry-fruits',
        img1: '/products/masala/dryFruits/3/1.webp',
        life: '180 days',
        origin:'India',
    },
    {
        name:"Daily Good Cardamom %2F Elachi Green",
        discountedPrice: 239,   
        price: 249,
        discount: 4,
        unit:'50 g',
        model: "Daily Good",
        subcategory: 'whole-spices-seasonings',
        category: 'masala-dry-fruits',
        img1: '/products/masala/wholeSpices/1/1.webp',
        description: "Daily Good Cardamom Green (Elachi) - Cardamom, also known as elachi, is a versatile spice that's used in cuisines around the world. It has a warm, sweet flavor and floral aroma that adds depth to a variety of dishes. Whether used in desserts, curries, or beverages, it's sure to add a delicious twist to your favorite recipes. Plus, it's packed with antioxidants and other nutrients that promote good health.",
        life: '180 days',
        origin:'India',
        manufacturer:'KTPL',
        manufacturerAddress:'Kiranakart Technologies Private Limited, 4th Floor, Wework Chromium-Powai, Jogeshwari Vikhroli Link Rd, Raje Sambhaji Nagar, Mumbai-400076',
    },
    {
        name:"On1y Cardamom",
        discountedPrice: 148,   
        price: 199,
        discount: 25,
        unit:'50 g',
        model: "On1y",
        subcategory: 'whole-spices-seasonings',
        category: 'masala-dry-fruits',
        img1: '/products/masala/wholeSpices/2/1.webp',
        life: '12 months',
        origin:'India',
        manufacturer:'Indian Products Pvt. Ltd.',
    },
    {
        name:"Shasha Small Green Cardamom Whole%2FElaichi - From The House Of Pansari",
        discountedPrice: 244,   
        price: 375,
        discount: 34,
        unit:'50 g',
        model: "Shasha",
        subcategory: 'whole-spices-seasonings',
        category: 'masala-dry-fruits',
        img1: '/products/masala/wholeSpices/3/1.webp',
        description: "Elevate your culinary creations with Shasha Small Green Cardamom! Sourced from the house of Pansari, these premium quality cardamom pods are known for their intense aroma and bold flavor. Whether used in desserts, beverages, or savory dishes, they add a delightful hint of sweetness and warmth that enhances the taste of your favorite recipes.",
        life: '15 months',
        origin:'India',
        manufacturer:'Pansari Industry Private Limited',
    },
    {
        name:"Uttam Sugar Sulphurless Sugar",
        discountedPrice: 269,   
        price: 325,
        discount: 17,
        unit:'5 kg',
        model: "Uttam Sugar",
        subcategory: 'salt-sugar-jaggery',
        category: 'masala-dry-fruits',
        img1: '/products/masala/salt/1/1.webp',
        description: "UTTAM SUGAR is made from high quality sun-ripened sugarcane, irrigated by the sweet waters of the Ganga, Harvested at peak maturity and speedily transported to retain its freshness, it is processed in the latest plant using world class UTTAM technology resulting in ultra sweet, ultra pure sugar, untouched by hand ensuring complete hygienic.",
        life: '24 months',
        origin:'India',
        manufacturer:'Uttam Sugar Mills Ltd',
        manufacturerAddress:'Uttam Sugar Mills Ltd, Libberheri, Haridwar Uttarakhand -247656.',
    },
    {
        name:"Fortune Sugar",
        discountedPrice: 265,   
        price: 320,
        discount: 17,
        unit:'5 kg',
        model: "Fortune",
        subcategory: 'salt-sugar-jaggery',
        category: 'masala-dry-fruits',
        img1: '/products/masala/salt/2/1.webp',
        description: "Fortune Fine Grain Sugar is untouched by hand and is made using a sulphur less process. The sugar is of premium quality and the crystals are sparkling white and easy to dissolve. This is processed keeping all the international standards of hygiene and purity in place. It is made with 100% cane sugar. Sugar is made by refining and processing sugarcane juice.",
        life: '24 months',
        origin:'India',
        manufacturer:'Adani Wilmar Limited',
        manufacturerAddress:'Adani Wilmar Limited, Adani Corporate House, Shantigram, Near Vaishnodevi Circle, S G Highway, Ahmedabad-382421, Gujarat, India.',
    },
    {
        name:"Daily Good Medium Sugar",
        discountedPrice: 289,   
        price: 340,
        discount: 15,
        unit:'5 kg',
        model: "Daily Good",
        subcategory: 'salt-sugar-jaggery',
        category: 'masala-dry-fruits',
        img1: '/products/masala/salt/3/1.webp',
        description: "Daily Good Sugar M30 is a high-quality sugar that's perfect for sweetening your favorite beverages and desserts. Made from pure sugarcane juice, Daily Good Sugar M30 has a natural sweetness and a fine texture that's ideal for everyday use. Whether you're baking cookies, making lemonade, or stirring it into your morning coffee, Daily Good Sugar M30 adds the perfect touch of sweetness to any recipe. With its purity and quality, Daily Good Sugar M30 is the preferred choice of chefs and home cooks alike. Enjoy the sweetness of Daily Good Sugar M30 in every bite",
        life: '12 months',
        origin:'India',
        manufacturer:'KTPL',
        manufacturerAddress:'Kiranakart Technologies Private Limited, 4th Floor, Wework Chromium-Powai, Jogeshwari Vikhroli Link Rd, Raje Sambhaji Nagar, Mumbai-400076.',
    },
    {
        name:"Farmley Mix Dried Berries",
        discountedPrice: 302,   
        price: 349,
        discount: 13,
        unit:'200 g',
        model: "Farmley",
        subcategory: 'dehydrated-dried',
        category: 'masala-dry-fruits',
        img1: '/products/masala/dehyadrated/1/1.webp',
        description: "Cranberry, black currant, mango, goji berry, black raisins, blueberry, kiwi, strawberry - the finest mix of berries & dried fruits is the exotic snack for all occasions. Each ingredient is individually sourced and combined to bring out that burst of perfect flavour in every mouthful. Packed with antioxidants, this snack is great for your skin and health-get that berrylicious glow. Eat as a snack, especially when you get sweet cravings. This superfood contains no artificial additives, no chemicals, no preservatives - just 100% naturally sourced nuts, seeds and berries.",
        life: '9 months',
        origin:'India',
        manufacturer:'Connedit Business Solutions Private Limited',
        manufacturerAddress:'Connedit Business Solutions Private Limited, Plot No 86, Okhla Industrial Estate, Phase - III, New Delhi 110020.',
    },
    {
        name:"Happilo Premium Dried Californian Blueberries",
        discountedPrice: 420,   
        price: 485,
        discount: 13,
        unit:'150 g',
        model: "Happilo",
        subcategory: 'dehydrated-dried',
        category: 'masala-dry-fruits',
        img1: '/products/masala/dehyadrated/2/1.webp',
        description: "Treat yourself to the delicious and nutritious taste of Happilo Premium Dried Californian Blueberries. These plump and juicy blueberries are carefully dried to perfection, locking in their natural sweetness and flavor. Whether you're enjoying them as a snack, adding them to your morning oatmeal, or baking them into your favorite desserts, Happilo Premium Dried Californian Blueberries are sure to delight your taste buds and satisfy your cravings for something sweet.",
        life: '12 months',
        origin:'India',
        manufacturer:'Happilo International Pvt Ltd',
        manufacturerAddress:'Happilo International Pvt Ltd, 7, 1st floor, Yeshwantpur, Bangalore 560022.',
    },
    {
        name:"Happilo Premium Turkish Apricots",
        discountedPrice: 325,   
        price: 365,
        discount: 10,
        unit:'200 g',
        model: "Happilo",
        subcategory: 'dehydrated-dried',
        category: 'masala-dry-fruits',
        img1: '/products/masala/dehyadrated/3/1.webp',
        description: "Indulge in the sweet and chewy goodness of Happilo Premium Turkish Apricots. These plump and juicy apricots are sourced from the finest orchards in Turkey and carefully sun-dried to preserve their natural flavor and nutrients. Whether you're snacking on them straight out of the bag, adding them to your morning cereal, or incorporating them into your favorite recipes, Happilo Premium Turkish Apricots are sure to satisfy your sweet cravings and nourish your body.",
        life: '12 months',
        origin:'India',
        manufacturer:'Happilo International Pvt Ltd',
        manufacturerAddress:'Happilo International Pvt Ltd, 7, 1st floor, Yeshwantpur, Bangalore 560022.',
    },
    {
        name:"Farmley Mix Dry Fruits Panchmeva Superfood Healthy Snacks",
        discountedPrice: 425,   
        price: 519,
        discount: 18,
        unit:'405 g',
        model: "Farmley Mix",
        subcategory: 'dates-seeds',
        category: 'masala-dry-fruits',
        img1: '/products/masala/dates/1/1.webp',
        description: "Almonds (badam), cashews (kaju), dates (chuhara), seedless black raisin, green raisin (kishmish) - the finest medley of nuts is the healthiest way to address those anytime hunger pangs. Each ingredient is individually sourced from farmers and combined to bring out that burst of perfect flavour in every mouthful. Packed with vegan proteins and high dietary fibre, this snack is the love of all vegans and fitness enthusiasts. This superfood contains no artificial additives, no chemicals, no preservatives - just 100% naturally sourced & flavourful nuts.",
        life: '9 months',
        origin:'India',
        manufacturer:'Connedit Business Solutions Private Limited',
        manufacturerAddress:'Connedit Business Solutions Private Limited, Plot No 86, Okhla Industrial Estate, Phase - III, New Delhi 110020.',
    },
    {
        name:"Khari Foods Mejdoul Dates %2F Khajoor",
        discountedPrice: 599,   
        unit:'200 g',
        model: "Khari",
        subcategory: 'dates-seeds',
        category: 'masala-dry-fruits',
        img1: '/products/masala/dates/2/1.webp',
        description: "Khari Foods Medjool dates are the kings and queens of the date world. Mejdoul dates are bigger and have a darker richer color than normal dates. They are chewy with a sweet flavor. Dates are extremely nutritious and contain several vitamins and minerals in addition to fibre and antioxidants.",
        life: '6 months',
        origin:'India',
        manufacturer:'Grahil Wellness Pvt Ltd',
        manufacturerAddress:'Delhi',
    },
    {
        name:"Khari Foods Berry Dried Mix",
        discountedPrice: 649,     
        price: 675,
        discount: 3,
        unit:'500 g',
        model: "Khari",
        subcategory: 'dates-seeds',
        category: 'masala-dry-fruits',
        img1: '/products/masala/dates/3/1.webp',
        description: "Indulge in Khari Foods vibrant blend of 5 dried berries cranberries blueberries blackberries cherries and strawberries. Packed with natural sweetness and devoid of sugar or preservatives this wholesome mix is the perfect guiltfree healthy snack for discerning Indian consumers. Savor the goodness of nature with every bite as Khari Foods brings you a delightful fusion of flavors in one nutritious package.",
        life: '180 days',
        origin:'India',
        manufacturer:'Grahil Wellness Pvt Ltd',
        manufacturerAddress:'Delhi',
    },
    
]

export const updateProducts = (category:string,subcategory:string,setProduct)=>{
    const categoryProducts = products.filter(item=>{
        return item.category === category
    })
    const subcategoryProducts = categoryProducts.filter(item=>{
        return item.subcategory === subcategory
    })
    return setProduct(subcategoryProducts)
}

export const getProduct = (product:string,setProduct)=>{
    const parsedProduct = product.replace('%25','%').replace('%2C',',').replace('%2F','/')
    console.log(parsedProduct, 'okay')
    const productNew = products.filter(item=>{
        const newName = item.name.replace('%25','%').replace('%2F','/')
        return newName === parsedProduct
    })
    const productDetails = productNew[0]
    console.log(productDetails, 'okay')
    return setProduct(productDetails)
}